version: '3.7'
services:
  api:
    build: .
    restart: always
    volumes:
      - .:/api
    command: ./api
    ports:
      - 80:3000

  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb

volumes:
  influx-data:

    # <measurement>[,<tag-key>=<tag-value>...] <field-key>=<field-value>[,<field2-key>=<field2-value>...] [unix-nano-timestamp]
    # INSERT pet,name=miau presence=false